### ISSUE TITLE
More prominent link to main bout-dev repo 

### ISSUE THREAD

**Issue by d7919** [boutproject/boutproject.github.io#10]
Currently it can take quite a bit of browsing to find a link to the actual code repo, Can we add a link on the main page and/or the about page that takes browsers direct to the github repo (master?)?

**Comment by ZedThree** [comment]
Could use the classic "fork me on github" ribbon?
https://github.com/blog/273-github-ribbons

The white one (very last) doesn't look too bad.

**Comment by JosephThomasParker** [comment]
I think we should should have a big "Download" link in the main box on the front page, as well as the "fork me" banner.

Personally, I think the red is more striking, though it might be a little dark.



![red](https://cloud.githubusercontent.com/assets/15211161/23613136/11651d1a-0276-11e7-8586-79d4d5ca7020.png)
![white](https://cloud.githubusercontent.com/assets/15211161/23613139/155fa340-0276-11e7-9edc-182d5d7a11b9.png)

**Comment by ZedThree** [comment]
Big download button works for me.
