### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by d7919** [boutproject/boutproject.github.io#11]
This can be an issue for any broken links that are found.

Currently 

* Download/ Other versions/ "Ben Dudson" to https://github.com/bendudson/BOUT-dev doesn't exist.

**Comment by ZedThree** [comment]
Oops, thought I'd caught that. Must've lost it when I was doing all the rebasing.

**Comment by d7919** [comment]
The text and links around "Previously, separate repositories were available for past releases. These are no longer maintained." might need changing as well. For example the first bullet says "The stable version" but links to the BOUT-2 repository (it's stable but not the current stable version).

**Comment by d7919** [comment]
Under documentation "If you would like to contribute to these pages please contact one of the developers" is a link to email Ben, should it be something else (like see the contributing guide or email the google group)?

All other links seem to work fine (although I've not tested those on publications).

**Comment by d7919** [comment]
The headings on the new applications page are links but don't seem to point to pages which exist.

**Comment by bendudson** [comment]
Ah, not links. The colour does make them look like links though

**Comment by dschwoerer** [comment]
Isn't that basically as bad as broken links?

**Comment by d7919** [comment]
They do appear as links for me, I can click on them and they take me to a 404 page.

**Comment by bendudson** [comment]
Yes it is. Sorry, needed to get material on the website asap for a meeting this morning, and no way to test apart from on the live website.

-------- Original Message --------

**Comment by ZedThree** [comment]
Oops, I think it's due to how I've set it up and jekyll trying to be clever.

**Comment by ZedThree** [comment]
Applications pages are sorted in #15 

Other stuff should be sorted in #17  -- could do with a second pair of eyes looking over it before merging though

**Comment by bshanahan** [comment]
Can this be closed?
