### ISSUE TITLE
"Latest posts" is a place-holder 

### ISSUE THREAD

**Issue by JosephThomasParker** [boutproject/boutproject.github.io#16]
The only "latest post" reads "Welcome to the test of the shiny new BOUT website", and links to a page asking for opinions on the theme...  What recent news could go here?  An advert for a recent paper?  Details of BUG meetings?

**Comment by ZedThree** [comment]
Adverts for recent papers sounds like a good idea. General announcements (e.g. release of new version) is a good bet too.

Also, we're not actually tied to having the posts bit -- getting rid of it would save us from having to keep it updated.
