### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boutproject.github.io#26]
It would be nice to have a [favicon](https://en.wikipedia.org/wiki/Favicon)

**Comment by ZedThree** [comment]
Maybe just a capital "B" in the website blue?

**Comment by JosephThomasParker** [comment]
Or B++, with the pluses stacked?

**Comment by dschwoerer** [comment]
Which blue?
#2196f3 (Blue of BOUT++Project Plasma simulation in ...)
#2979ff (Blue of menu)
#256de5 (Blue of selected entry)

[Here is a possible implementation](https://omadesala.physics.dcu.ie/~dave/fav.html)

**Comment by ZedThree** [comment]
#2196f3 blue is the right one, I think.
Can you use the Roboto font? http://materializecss.com/typography.html

**Comment by dschwoerer** [comment]
now with the first blue.

I tried to use Roboto, but for the 16x16 version the font is 1 px to wide, so that I needed to squeeze it a bit, to make space for the ++
the 32 px version has the unchanged roboto font.
Unfortunately it is not possible to upload .ico files to github ...
