### ISSUE TITLE
Menu too wide

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boutproject.github.io#28]
The menu at the top is sometimes not rendered correctly.
If there is not enough space, a part of the menu is hidden behind the 'BOUT++ Project' title.

**Comment by ZedThree** [comment]
It's pretty annoying! I think this can be tweaked with a hard coded number.
I've not yet looked into whether it can calculate how much space it needs
and size things accordingly. Web development is awful.

**Comment by d7919** [comment]
I think it's `$medium-screen` and related variables in `https://github.com/boutproject/boutproject.github.io/blob/master/assets/css/components/_variables.scss`

In principle it's possible to do calculations in the scss, which may be helpful. In practice I'm not sure we're really going to be able to do this automatically and we might be best off resorting to just hard-coding some numbers (on the basis that the headings etc. will settle down and not change regularly).

Note there are also issues if you keep on narrowing the screen; the fork banner and mobile menu items can start to intersect/overlay the logo/title as well.
