### ISSUE TITLE
Update workshop links

### ISSUE THREAD

**Issue by d7919** [boutproject/boutproject.github.io#41]
Most recent workshop links are for 2016 -- can we provide links to any newer workshops.

We may also want to advertise the upcoming 2018 workshop?

**Comment by JosephThomasParker** [comment]
I've pushed a branch that starts doing this: https://github.com/boutproject/boutproject.github.io/tree/workshop18

This just makes a Workshop 2018 page in the same format as for other years (and the same info as the 2016 workshop...), and adds a Workshop 2018 button to the main banner.

**Comment by JosephThomasParker** [comment]
I quite like the idea of having a button on the banner as an advert, e.g.

![screenshot from 2018-09-13 09-52-48](https://user-images.githubusercontent.com/15211161/45478019-dc7d8580-b73a-11e8-9760-19f8c02c4e34.png)

but I don't know how to make just one button different, without editing the git-ignored `_site/index.html`.  @ZedThree?

**Comment by d7919** [comment]
I think you could probably do it by editing `_index/header.html` -- there's some example logic already that is looking at meta-data in `folder/index.md` to decide if the entry should get a link etc. I think you could probably add an extra bit of meta-data (or a new value for existing meta-data) to say please make be bold.

(I think @ZedThree is out of email contact currently).

**Comment by JosephThomasParker** [comment]
Thanks!

**Comment by bshanahan** [comment]
I think this is closed in Issue [#43](https://github.com/boutproject/boutproject.github.io/pull/43)
