### ISSUE TITLE
Bullet points look weird in some browsers

### ISSUE THREAD

**Issue by ZedThree** [boutproject/boutproject.github.io#7]
Check blank lines after items/list

**Comment by JosephThomasParker** [comment]
I was just thinking this... I think the last answer [here](http://meta.stackexchange.com/questions/192894/multi-paragraph-list-items-or-preventing-numbered-list-auto-formatting) does the trick.

**Comment by ZedThree** [comment]
I'm currently playing about with the CSS to try and make it work without having to put html tags straight in the markdown
